package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contato generated by hbm2java
 */
@Entity
@Table(name = "contato", schema = "public")
public class Contato implements java.io.Serializable {

    @Id
    @Column(name = "idContato")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idcontato;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_contato_idtipo_contato", nullable = false)
    private Tipocontato tipocontato;
    @Column(name = "descricao", nullable = false, length = 60)
    private String descricao;

    public Contato() {
    }

    public Contato(int idcontato, Tipocontato tipocontato, String descricao) {
        this.idcontato = idcontato;
        this.tipocontato = tipocontato;
        this.descricao = descricao;
    }

    public Contato(int idcontato, Tipocontato tipocontato, String descricao, Set pessoas) {
        this.idcontato = idcontato;
        this.tipocontato = tipocontato;
        this.descricao = descricao;
       
    }

    public int getIdcontato() {
        return this.idcontato;
    }

    public void setIdcontato(int idcontato) {
        this.idcontato = idcontato;
    }

    public Tipocontato getTipocontato() {
        return this.tipocontato;
    }

    public void setTipocontato(Tipocontato tipocontato) {
        this.tipocontato = tipocontato;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
}
