package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Devolucao generated by hbm2java
 */
@Entity
@Table(name = "devolucao", schema = "public")
public class Devolucao implements java.io.Serializable {

    @Id
    @Column(name = "idDevolucao")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int iddevolucao;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "locacao_idlocacao", nullable = false)
    private Locacao locacao;
    @Temporal(TemporalType.DATE)
    @Column(name = "dt_devolucao", length = 13)
    private Date dtDevolucao;
    @Column(name = "km_rodados", nullable = false)
    private int kmRodados;

    public Devolucao() {
    }

    public Devolucao(int iddevolucao, Locacao locacao, int kmRodados) {
        this.iddevolucao = iddevolucao;
        this.locacao = locacao;
        this.kmRodados = kmRodados;
    }

    public Devolucao(int iddevolucao, Locacao locacao, Date dtDevolucao, int kmRodados) {
        this.iddevolucao = iddevolucao;
        this.locacao = locacao;
        this.dtDevolucao = dtDevolucao;
        this.kmRodados = kmRodados;
    }

    public int getIddevolucao() {
        return this.iddevolucao;
    }

    public void setIddevolucao(int iddevolucao) {
        this.iddevolucao = iddevolucao;
    }

    public Locacao getLocacao() {
        return this.locacao;
    }

    public void setLocacao(Locacao locacao) {
        this.locacao = locacao;
    }

    public Date getDtDevolucao() {
        return this.dtDevolucao;
    }

    public void setDtDevolucao(Date dtDevolucao) {
        this.dtDevolucao = dtDevolucao;
    }

    public int getKmRodados() {
        return this.kmRodados;
    }

    public void setKmRodados(int kmRodados) {
        this.kmRodados = kmRodados;
    }
}
