package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Documentos generated by hbm2java
 */
@Entity
@Table(name = "documentos", schema = "public")
public class Documentos implements java.io.Serializable {

    @Id
    @Column(name = "iddocumentos")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int iddocumentos;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "veiculo_idveiculo", nullable = false)
    private Veiculo veiculo;
    @Column(name = "descricao", nullable = false, length = 45)
    private String descricao;
    
    @Temporal(TemporalType.DATE)
    @Column(name = "dt_inclusao", nullable = false, length = 13)
    private Date dtInclusao;
    @Column(name = "tipo", nullable = false, length = 45)
    private String tipo;
    @Column(name = "observacoes", length = 100)
    private String observacoes;

    public Documentos() {
    }

    public Documentos(int iddocumentos, Veiculo veiculo, String descricao, Date dtInclusao, String tipo) {
        this.iddocumentos = iddocumentos;
        this.veiculo = veiculo;
        this.descricao = descricao;
        this.dtInclusao = dtInclusao;
        this.tipo = tipo;
    }

    public Documentos(int iddocumentos, Veiculo veiculo, String descricao, Date dtInclusao, String tipo, String observacoes) {
        this.iddocumentos = iddocumentos;
        this.veiculo = veiculo;
        this.descricao = descricao;
        this.dtInclusao = dtInclusao;
        this.tipo = tipo;
        this.observacoes = observacoes;
    }

    public int getIddocumentos() {
        return this.iddocumentos;
    }

    public void setIddocumentos(int iddocumentos) {
        this.iddocumentos = iddocumentos;
    }

    public Veiculo getVeiculo() {
        return this.veiculo;
    }

    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }

    
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Date getDtInclusao() {
        return this.dtInclusao;
    }

    public void setDtInclusao(Date dtInclusao) {
        this.dtInclusao = dtInclusao;
    }

    
    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    public String getObservacoes() {
        return this.observacoes;
    }

    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
}
