package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "endereco", schema = "public")
public class Endereco implements java.io.Serializable {

    @Id
    @Column(name = "idendereco")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idendereco;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cidade_idcidade", nullable = false)
    private Cidade cidade;
    @Column(name = "descricao", nullable = false, length = 45)
    private String descricao;
    @Column(name = "bairro", nullable = false, length = 45)
    private String bairro;
    @Column(name = "cep", nullable = false, length = 45)
    private String cep;
    @Column(name = "complemento", length = 45)
    private String complemento;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
    private Set<Pessoa> pessoas = new HashSet(0);

    public Endereco() {
    }

    public Endereco(int idendereco, Cidade cidade, String descricao, String bairro, String cep) {
        this.idendereco = idendereco;
        this.cidade = cidade;
        this.descricao = descricao;
        this.bairro = bairro;
        this.cep = cep;
    }

     public Endereco(int idendereco, entidade.Cidade cidade, String descricao, String bairro, String cep, String complemento, Set pessoas) {
       this.idendereco = idendereco;
       this.cidade = cidade;
       this.descricao = descricao;
       this.bairro = bairro;
       this.cep = cep;
       this.complemento = complemento;
       this.pessoas = pessoas;
    }

    public int getIdendereco() {
        return this.idendereco;
    }

    public void setIdendereco(int idendereco) {
        this.idendereco = idendereco;
    }

    public Cidade getCidade() {
        return this.cidade;
    }

    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    public String getComplemento() {
        return this.complemento;
    }

    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    public Set getPessoas() {
        return this.pessoas;
    }

    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }

}
