package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Funcao generated by hbm2java
 */
@Entity
@Table(name = "funcao", schema = "public")
public class Funcao implements java.io.Serializable {

    @Id
    @Column(name = "idfuncao")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idfuncao;
    @Column(name = "descricao", nullable = false, length = 45)
    private String descricao;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="funcao")
    private Set<Funcionario> funcionarios = new HashSet(0);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="funcao")
	 private Set<Permissao> permissaos = new HashSet(0);
	
    public Funcao() {
    }

    public Funcao(int idfuncao, String descricao) {
        this.idfuncao = idfuncao;
        this.descricao = descricao;
    }

      public Funcao(int idfuncao, String descricao, Set permissaos, Set funcionarios) {
       this.idfuncao = idfuncao;
       this.descricao = descricao;
       this.permissaos = permissaos;
       this.funcionarios = funcionarios;
    }
   

    public int getIdfuncao() {
        return this.idfuncao;
    }

    public void setIdfuncao(int idfuncao) {
        this.idfuncao = idfuncao;
    }

    
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
	
	 public Set getPermissaos() {
        return this.permissaos;
    }
    
    public void setPermissaos(Set permissaos) {
        this.permissaos = permissaos;
    }
}
