package entidade;
// Generated 04/10/2015 19:28:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name="permissao"
    ,schema="public"
)
public class Permissao  implements java.io.Serializable {

 @Id
    @Column(name = "idPermissao")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private int idpermissao;
 @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idfuncao")
     private Funcao funcao;
 @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpessoa")
     private Pessoa pessoa;
 @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtela", nullable=false)
     private Tela tela;
  @Column(name="ler", nullable=false)
     private boolean ler;
      @Column(name="inserir", nullable=false)
     private boolean inserir;
       @Column(name="editar", nullable=false)
     private boolean editar;
       @Column(name="inativar", nullable=false)
     private boolean inativar;

    public Permissao() {
    }

	
    public Permissao(int idpermissao, Tela tela, boolean ler, boolean inserir, boolean editar, boolean inativar) {
        this.idpermissao = idpermissao;
        this.tela = tela;
        this.ler = ler;
        this.inserir = inserir;
        this.editar = editar;
        this.inativar = inativar;
    }
    public Permissao(int idpermissao, Funcao funcao, Pessoa pessoa, Tela tela, boolean ler, boolean inserir, boolean editar, boolean inativar) {
       this.idpermissao = idpermissao;
       this.funcao = funcao;
       this.pessoa = pessoa;
       this.tela = tela;
       this.ler = ler;
       this.inserir = inserir;
       this.editar = editar;
       this.inativar = inativar;
    }
   
    
    public int getIdpermissao() {
        return this.idpermissao;
    }
    
    public void setIdpermissao(int idpermissao) {
        this.idpermissao = idpermissao;
    }


    public Funcao getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
    }


    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }


    public Tela getTela() {
        return this.tela;
    }
    
    public void setTela(Tela tela) {
        this.tela = tela;
    }

    
   
    public boolean isLer() {
        return this.ler;
    }
    
    public void setLer(boolean ler) {
        this.ler = ler;
    }

    
   
    public boolean isInserir() {
        return this.inserir;
    }
    
    public void setInserir(boolean inserir) {
        this.inserir = inserir;
    }

    
   
    public boolean isEditar() {
        return this.editar;
    }
    
    public void setEditar(boolean editar) {
        this.editar = editar;
    }

    
    
    public boolean isInativar() {
        return this.inativar;
    }
    
    public void setInativar(boolean inativar) {
        this.inativar = inativar;
    }




}


