package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa", schema = "public")
public class Pessoa implements java.io.Serializable {

    @Id
    @Column(name = "idpessoa")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idpessoa;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "endereco_idendereco", nullable = false)
    private Endereco endereco;
    @Column(name = "nome", nullable = false, length = 45)
    private String nome;
    @OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
    private Pessoajuridica pessoajuridica;
    @OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
    private Cliente cliente;
    @OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
    private Pessoafisica pessoafisica;
    @OneToOne(fetch = FetchType.LAZY, mappedBy = "pessoa")
    private Funcionario funcionario;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
    private Set<Log> logs = new HashSet(0);
	@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
	private Set<Permissao> permissaos = new HashSet(0);
	@OneToMany(fetch=FetchType.LAZY, mappedBy="pessoa")
private Set<Auditoria> auditorias = new HashSet(0);
@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="contato_pessoa", schema="public", joinColumns = { 
        @JoinColumn(name="pessoa_idpessoa", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="contato_idcontato", nullable=false, updatable=false) })
  
private Set<Contato> contatos = new HashSet(0);

    public Pessoa() {
    }

    public Pessoa(int idpessoa, Endereco endereco, String nome) {
        this.idpessoa = idpessoa;
        this.endereco = endereco;
        this.nome = nome;
    }

  
         public Pessoa(int idpessoa, Endereco endereco, String nome, Cliente cliente, Pessoajuridica pessoajuridica, Set logs, Set contatos, Pessoafisica pessoafisica, Set permissaos, Funcionario funcionario, Set auditorias) {
       this.idpessoa = idpessoa;
       this.endereco = endereco;
       this.nome = nome;
       this.cliente = cliente;
       this.pessoajuridica = pessoajuridica;
       this.logs = logs;
       this.contatos = contatos;
       this.pessoafisica = pessoafisica;
       this.permissaos = permissaos;
       this.funcionario = funcionario;
       this.auditorias = auditorias;
    }

    public int getIdpessoa() {
        return this.idpessoa;
    }

    public void setIdpessoa(int idpessoa) {
        this.idpessoa = idpessoa;
    }

    public Endereco getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Pessoajuridica getPessoajuridica() {
        return this.pessoajuridica;
    }

    public void setPessoajuridica(Pessoajuridica pessoajuridica) {
        this.pessoajuridica = pessoajuridica;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Pessoafisica getPessoafisica() {
        return this.pessoafisica;
    }

    public void setPessoafisica(Pessoafisica pessoafisica) {
        this.pessoafisica = pessoafisica;
    }

    public Funcionario getFuncionario() {
        return this.funcionario;
    }

    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
 
    
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }
	
	 public Set getAuditorias() {
        return this.auditorias;
    }
    
    public void setAuditorias(Set auditorias) {
        this.auditorias = auditorias;
    }

	   public Set getContatos() {
        return this.contatos;
    }
    
    public void setContatos(Set contatos) {
        this.contatos = contatos;
    }
	
	 public Set getPermissaos() {
        return this.permissaos;
    }
    
    public void setPermissaos(Set permissaos) {
        this.permissaos = permissaos;
    }
	
	
}
