package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Statusveiculo generated by hbm2java
 */
@Entity
@Table(name = "statusveiculo", schema = "public")
public class Statusveiculo implements java.io.Serializable {

    @Id
    @Column(name = "idstatusveiculo")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idstatusveiculo;
    @Column(name = "descricao", nullable = false, length = 100)
    private String descricao;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="statusveiculo")
    private Set<Veiculo> veiculos = new HashSet(0);
 

    public Statusveiculo() {
    }

    public Statusveiculo(int idstatusVeiculo, String descricao) {
        this.idstatusveiculo = idstatusVeiculo;
        this.descricao = descricao;
        
    }

     public Statusveiculo(int idstatusveiculo, String descricao, Set veiculos) {
       this.idstatusveiculo = idstatusveiculo;
       this.descricao = descricao;
       this.veiculos = veiculos;
    }

    public int getIdstatusVeiculo() {
        return this.idstatusveiculo;
    }

    public void setIdstatusVeiculo(int idstatusVeiculo) {
        this.idstatusveiculo = idstatusVeiculo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    
    public Set getVeiculos() {
        return this.veiculos;
    }
    
    public void setVeiculos(Set veiculos) {
        this.veiculos = veiculos;
    }


}
