package entidade;
// Generated 04/10/2015 19:28:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tela generated by hbm2java
 */
@Entity
@Table(name = "tela", schema = "public"
)
public class Tela implements java.io.Serializable {

    @Id
    @Column(name = "idTela")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idtela;
    @Column(name = "descricao", length = 200)
    private String descricao;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tela")
    private Set<Permissao> permissaos = new HashSet(0);

    public Tela() {
    }

    public Tela(int idtela) {
        this.idtela = idtela;
    }

    public Tela(int idtela, String descricao, Set permissaos) {
        this.idtela = idtela;
        this.descricao = descricao;
        this.permissaos = permissaos;
    }

    public int getIdtela() {
        return this.idtela;
    }

    public void setIdtela(int idtela) {
        this.idtela = idtela;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set getPermissaos() {
        return this.permissaos;
    }

    public void setPermissaos(Set permissaos) {
        this.permissaos = permissaos;
    }

}
