package entidade;
// Generated 17/08/2015 19:54:52 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoveiculo generated by hbm2java
 */
@Entity
@Table(name = "tipoveiculo", schema = "public")
public class Tipoveiculo implements java.io.Serializable {

    @Id
    @Column(name = "idtipoVeiculo")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int idtipoVeiculo;
    @Column(name = "descricao", nullable = false, length = 100)
    private String descricao;
    @Column(name = "valor_diaria", nullable = false, precision = 11)
    private BigDecimal valorDiaria;
    @Column(name = "observacoes", length = 100)
    private String observacoes;
    @Column(name = "especificacoes", nullable = false, length = 200)
    private String especificacoes;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoveiculo")
    private Set<Veiculo> veiculos = new HashSet(0);

    public Tipoveiculo() {
    }

    public Tipoveiculo(int idtipoVeiculo, String descricao, BigDecimal valorDiaria, String especificacoes) {
        this.idtipoVeiculo = idtipoVeiculo;
        this.descricao = descricao;
        this.valorDiaria = valorDiaria;
        this.especificacoes = especificacoes;
    }

    public Tipoveiculo(int idtipoVeiculo, String descricao, BigDecimal valorDiaria, String observacoes, String especificacoes, Set veiculos) {
        this.idtipoVeiculo = idtipoVeiculo;
        this.descricao = descricao;
        this.valorDiaria = valorDiaria;
        this.observacoes = observacoes;
        this.especificacoes = especificacoes;

    }

    public int getIdtipoVeiculo() {
        return this.idtipoVeiculo;
    }

    public void setIdtipoVeiculo(int idtipoVeiculo) {
        this.idtipoVeiculo = idtipoVeiculo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public BigDecimal getValorDiaria() {
        return this.valorDiaria;
    }

    public void setValorDiaria(BigDecimal valorDiaria) {
        this.valorDiaria = valorDiaria;
    }

    public String getObservacoes() {
        return this.observacoes;
    }

    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

    public String getEspecificacoes() {
        return this.especificacoes;
    }

    public void setEspecificacoes(String especificacoes) {
        this.especificacoes = especificacoes;
    }

    public Set getVeiculos() {
        return this.veiculos;
    }

    public void setVeiculos(Set veiculos) {
        this.veiculos = veiculos;
    }
}
